import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Download, RefreshCw, TrendingUp } from 'lucide-react';
const KEYS={packages:'agencyos:sales-packages:v1',deals:'agencyos:deal-tracker:v1',invoices:'agencyos:invoice-tracker:v1',projects:'agencyos:project-tracker:v1',expenses:'agencyos:expense-tracker:v1'};
const muted={color:'var(--viz-muted, #a1a1aa)',fontSize:13,lineHeight:1.55};
const card={border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:15};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))??fallback}catch{return fallback}}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function dateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function monthLabel(key){const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-IN',{month:'short',year:'2-digit'})}
export default function BusinessReports(){
 const [packages,setPackages]=useState([]),[deals,setDeals]=useState({}),[invoices,setInvoices]=useState([]),[projects,setProjects]=useState([]),[expenses,setExpenses]=useState([]),[notice,setNotice]=useState('');
 function refresh(){const p=read(KEYS.packages,[]),d=read(KEYS.deals,{}),i=read(KEYS.invoices,[]),t=read(KEYS.projects,[]),e=read(KEYS.expenses,[]);setPackages(Array.isArray(p)?p:[]);setDeals(d&&typeof d==='object'&&!Array.isArray(d)?d:{});setInvoices(Array.isArray(i)?i:[]);setProjects(Array.isArray(t)?t:[]);setExpenses(Array.isArray(e)?e:[]);setNotice('Reports refreshed from this browser’s saved records.')}
 useEffect(()=>{refresh();const f=()=>refresh();window.addEventListener('focus',f);return()=>window.removeEventListener('focus',f)},[]);
 const report=useMemo(()=>{
  const validInvoices=invoices.filter(i=>Number.isFinite(Number(i.amount))&&Number(i.amount)>0);
  const validExpenses=expenses.filter(e=>Number.isFinite(Number(e.amount))&&Number(e.amount)>0);
  const paid=validInvoices.filter(i=>i.status==='Paid').reduce((s,i)=>s+Number(i.amount),0);
  const businessExpenses=validExpenses.filter(e=>e.type==='Business').reduce((s,e)=>s+Number(e.amount),0);
  const personalExpenses=validExpenses.filter(e=>e.type==='Personal').reduce((s,e)=>s+Number(e.amount),0);
  const monthKey=dateKey(new Date());
  const monthPaid=validInvoices.filter(i=>i.status==='Paid'&&String(i.issueDate||'').slice(0,7)===monthKey).reduce((s,i)=>s+Number(i.amount),0);
  const monthBusinessExpenses=validExpenses.filter(e=>e.type==='Business'&&String(e.date||'').slice(0,7)===monthKey).reduce((s,e)=>s+Number(e.amount),0);
  const outstanding=validInvoices.filter(i=>['Sent','Overdue','Partially paid'].includes(i.status)).reduce((s,i)=>s+Number(i.amount),0);
  const won=packages.filter(p=>(deals[p.id]||{}).stage==='Won');
  const active=projects.filter(p=>!['Completed','On hold'].includes(p.status));
  const completed=projects.filter(p=>p.status==='Completed').length;
  const overdue=projects.filter(p=>p.dueDate&&p.dueDate<new Date().toISOString().slice(0,10)&&p.status!=='Completed').length;
  const months=[];const now=new Date();for(let offset=5;offset>=0;offset--){const d=new Date(now.getFullYear(),now.getMonth()-offset,1);months.push(dateKey(d))}
  const trend=months.map(key=>({key,label:monthLabel(key),amount:validInvoices.filter(i=>String(i.issueDate||'').slice(0,7)===key).reduce((s,i)=>s+Number(i.amount),0),paid:validInvoices.filter(i=>String(i.issueDate||'').slice(0,7)===key&&i.status==='Paid').reduce((s,i)=>s+Number(i.amount),0)}));
  return {invoiceCount:invoices.length,paid,outstanding,total:validInvoices.reduce((s,i)=>s+Number(i.amount),0),expenseCount:expenses.length,businessExpenses,personalExpenses,monthPaid,monthBusinessExpenses,monthNet:monthPaid-monthBusinessExpenses,wonCount:won.length,packages:packages.length,activeProjects:active.length,completed,overdue,trend,statuses:['Draft','Sent','Partially paid','Paid','Overdue','Cancelled'].map(status=>({status,count:invoices.filter(i=>i.status===status).length,amount:validInvoices.filter(i=>i.status===status).reduce((s,i)=>s+Number(i.amount),0)}))}
 },[packages,deals,invoices,projects,expenses]);
 const max=Math.max(1,...report.trend.map(x=>x.amount));
 function exportCsv(){
    const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
    const lines=[['Metric','Value'],['Invoice records',report.invoiceCount],['Recorded invoice total INR',report.total],['Marked paid INR',report.paid],['Outstanding INR',report.outstanding],['Business expenses INR',report.businessExpenses],['Personal expenses INR',report.personalExpenses],['Current month paid invoice records INR',report.monthPaid],['Current month business expenses INR',report.monthBusinessExpenses],['Current month paid less business expenses INR',report.monthNet],['Expense records',report.expenseCount],['Won deals',report.wonCount],['Sales packages',report.packages],['Active projects',report.activeProjects],['Completed projects',report.completed],['Overdue projects',report.overdue],[],['Month','Invoice records total INR','Invoices marked paid INR'],...report.trend.map(x=>[x.label,x.amount,x.paid]),[],['Invoice status','Count','Amount INR'],...report.statuses.map(x=>[x.status,x.count,x.amount])];
    const csv='\ufeff'+lines.map(row=>row.map(esc).join(',')).join('\r\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));
    const a=document.createElement('a');a.href=url;a.download='revoltz-business-report.csv';a.click();URL.revokeObjectURL(url);setNotice('CSV report exported.');
  }
 return <div style={{display:'grid',gap:20,maxWidth:1100}}>
 <header style={{display:'flex',gap:13,alignItems:'flex-start'}}><div style={{border:'1px solid var(--viz-border, #333)',borderRadius:13,padding:12}}><BarChart3 size={23}/></div><div><div style={{...muted,letterSpacing:'.14em',fontWeight:700}}>REVOLTZ AI · OWNER DASHBOARD</div><h1 style={{fontSize:32,margin:'4px 0 7px'}}>Business Reports</h1><p style={{...muted,margin:0}}>A quick view of invoice records, deals and delivery work saved in this browser. Invoice amounts are record totals—not audited revenue or a forecast.</p></div></header>
 <div style={{display:'flex',gap:9,flexWrap:'wrap'}}><button type="button" onClick={refresh} style={{display:'inline-flex',gap:7,alignItems:'center',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'9px 12px',background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer'}}><RefreshCw size={15}/> Refresh report</button><button type="button" onClick={exportCsv} style={{display:'inline-flex',gap:7,alignItems:'center',border:0,borderRadius:9,padding:'9px 12px',background:'var(--viz-accent, #3977dc)',color:'#fff',cursor:'pointer'}}><Download size={15}/> Export CSV</button></div>
 {notice&&<div role="status" style={{...muted,border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:10}}>{notice}</div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}>{[['Invoice records total',money(report.total)],['Marked paid',money(report.paid)],['Outstanding records',money(report.outstanding)],['Won deals',report.wonCount],['Active projects',report.activeProjects],['Overdue projects',report.overdue]].map(([label,value])=><div key={label} style={card}><div style={muted}>{label}</div><div style={{fontSize:24,fontWeight:750,marginTop:6}}>{value}</div></div>)}</div>
 <section style={card}><h2 style={{fontSize:19,margin:'0 0 6px'}}>Expense & cash snapshot</h2><p style={muted}>Current calendar month. “Paid invoice records less business expenses” is a simple internal snapshot, not profit: invoice status is user-entered and timing/taxes/refunds are not accounted for.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(175px,1fr))',gap:10,marginTop:12}}>{[['Business expenses (all time)',money(report.businessExpenses)],['Personal expenses (all time)',money(report.personalExpenses)],['Paid invoice records this month',money(report.monthPaid)],['Business expenses this month',money(report.monthBusinessExpenses)],['Paid less business expenses this month',money(report.monthNet)]].map(([label,value])=><div key={label} style={{...card,padding:12}}><div style={muted}>{label}</div><strong style={{display:'block',fontSize:20,marginTop:6}}>{value}</strong></div>)}</div></section>
 <section style={card}><div style={{display:'flex',alignItems:'center',gap:8}}><TrendingUp size={19}/><h2 style={{fontSize:19,margin:0}}>Six-month invoice record trend</h2></div><p style={muted}>Based on invoice issue dates and recorded amounts. This does not indicate when cash was received unless status is marked Paid.</p><div style={{display:'grid',gap:12,marginTop:18}}>{report.trend.map(item=><div key={item.key} style={{display:'grid',gridTemplateColumns:'62px minmax(50px,1fr) minmax(95px,auto)',gap:10,alignItems:'center'}}><span style={muted}>{item.label}</span><div style={{height:15,background:'var(--viz-border, #292929)',borderRadius:5,overflow:'hidden'}}><div title={money(item.amount)} style={{height:'100%',width:(item.amount/max*100)+'%',background:'var(--viz-accent, #3977dc)',minWidth:item.amount?3:0}}/></div><span style={{fontSize:12,textAlign:'right'}}>{money(item.amount)}<span style={{...muted,display:'block'}}>Paid {money(item.paid)}</span></span></div>)}</div>{!report.invoiceCount&&<p style={muted}>Add invoice records in Invoice Tracker to populate this chart.</p>}</section>
 <section style={card}><h2 style={{fontSize:19,margin:'0 0 12px'}}>Invoice status breakdown</h2><div style={{display:'grid',gap:0}}>{report.statuses.map(row=><div key={row.status} style={{display:'grid',gridTemplateColumns:'1fr 70px minmax(90px,auto)',gap:10,padding:'11px 0',borderBottom:'1px solid var(--viz-border, #222)',alignItems:'center'}}><span>{row.status}</span><span style={muted}>{row.count} records</span><strong style={{textAlign:'right'}}>{money(row.amount)}</strong></div>)}</div></section>
 <p style={muted}>Reports read browser-local records from AgencyOS. They do not sync across devices and are not accounting, tax, or audited financial statements. Export CSV regularly for backup.</p>
 </div>
}