import { useEffect, useMemo, useState } from 'react';
import { Download, History, Plus, Search, Trash2 } from 'lucide-react';

const KEY='agencyos:client-activity-log:v1';
const card={border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:14,background:'var(--viz-card, #151515)'};
const muted={color:'var(--viz-muted, #a1a1aa)',fontSize:13,lineHeight:1.55};
const field={width:'100%',boxSizing:'border-box',padding:'10px 11px',borderRadius:9,border:'1px solid var(--viz-border, #333)',background:'var(--viz-card, #151515)',color:'var(--viz-text, #f5f5f5)',font:'inherit'};
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const blank=()=>({client:'',date:today(),type:'Call',outcome:'Connected',summary:'',nextAction:'',nextDate:''});
function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string'):[]}catch{return []}}
function dateLabel(v){if(!v)return 'No date';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
export default function ClientActivityLog(){
 const [items,setItems]=useState(read);const [form,setForm]=useState(blank);const [query,setQuery]=useState('');const [typeFilter,setTypeFilter]=useState('All');const [notice,setNotice]=useState('');
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(items))}catch{setNotice('Browser storage is full; changes may not persist.') }},[items]);
 const visible=useMemo(()=>items.filter(x=>(typeFilter==='All'||x.type===typeFilter)&&(!query.trim()||[x.client,x.summary,x.nextAction,x.outcome,x.type].join(' ').toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||'').localeCompare(a.createdAt||'')),[items,query,typeFilter]);
 const upcoming=items.filter(x=>x.nextDate&&x.nextDate>=today()&&x.nextAction.trim()).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));
 function add(e){e.preventDefault();if(!form.client.trim()||!form.summary.trim()){setNotice('Enter a client or business name and a short interaction summary.');return}setItems(prev=>[{...form,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),client:form.client.trim().slice(0,140),summary:form.summary.trim().slice(0,2000),nextAction:form.nextAction.trim().slice(0,500),createdAt:new Date().toISOString()},...prev]);setForm(blank());setNotice('Interaction saved in this browser.')}
 function remove(id){setItems(prev=>prev.filter(x=>x.id!==id))}
 function exportCsv(){const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const rows=[['Client','Date','Type','Outcome','Summary','Next action','Next action date'],...items.map(x=>[x.client,x.date,x.type,x.outcome,x.summary,x.nextAction,x.nextDate])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='agencyos-client-activity.csv';a.click();URL.revokeObjectURL(url)}
 return <section style={{display:'grid',gap:16,maxWidth:1100,color:'var(--viz-text, #f5f5f5)'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><div style={{...card,padding:12}}><History size={23}/></div><div><div style={{...muted,letterSpacing:'.13em',fontWeight:700}}>REVOLTZ AI · CLIENT RELATIONSHIPS</div><h1 style={{fontSize:30,margin:'4px 0 6px'}}>Client Activity Log</h1><p style={{...muted,margin:0,maxWidth:700}}>Keep a searchable history of client calls, meetings, emails and decisions, with the next action recorded alongside each interaction.</p></div></div><button type="button" onClick={exportCsv} disabled={!items.length} style={{display:'inline-flex',alignItems:'center',gap:8,padding:'10px 13px',borderRadius:9,border:'1px solid var(--viz-border, #333)',background:'transparent',color:'inherit',font:'inherit',cursor:'pointer',opacity:items.length?1:.5}}><Download size={16}/> Export CSV</button></header>
  {notice&&<div role="status" style={{...card,...muted}}>{notice}</div>}
  <form onSubmit={add} style={{...card,display:'grid',gap:12}}><h2 style={{fontSize:19,margin:0}}>Log an interaction</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,180px),1fr))',gap:10}}>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Client / business<input style={field} required maxLength={140} value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="e.g. Acharya's Kitchen"/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Date<input style={field} type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Interaction type<select style={field} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['Call','Meeting','Email','WhatsApp','Demo','Other'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Outcome<select style={field} value={form.outcome} onChange={e=>setForm({...form,outcome:e.target.value})}>{['Connected','No response','Interested','Needs follow-up','Proposal requested','Won','Lost','Other'].map(x=><option key={x}>{x}</option>)}</select></label>
  </div><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Summary / notes<textarea style={{...field,minHeight:85,resize:'vertical'}} required maxLength={2000} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="What did you discuss? Any decisions or objections?"/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,220px),1fr))',gap:10}}><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Next action<input style={field} maxLength={500} value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})} placeholder="e.g. Send revised proposal"/></label><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Next action date<input style={field} type="date" value={form.nextDate} onChange={e=>setForm({...form,nextDate:e.target.value})}/></label></div><div><button type="submit" style={{display:'inline-flex',alignItems:'center',gap:8,padding:'10px 14px',border:0,borderRadius:9,background:'var(--viz-accent, #6865f2)',color:'#fff',font:'inherit',fontWeight:700,cursor:'pointer'}}><Plus size={16}/> Save interaction</button></div></form>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}>{[['Total interactions',items.length],['Clients recorded',new Set(items.map(x=>x.client.toLowerCase())).size],['Upcoming next actions',upcoming.length]].map(([label,value])=><div key={label} style={card}><div style={muted}>{label}</div><div style={{fontSize:24,fontWeight:800,marginTop:6}}>{value}</div></div>)}</div>
  <section style={{display:'grid',gap:10}}><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><label style={{display:'flex',alignItems:'center',gap:8,flex:'1 1 230px',...card,padding:'7px 10px'}}><Search size={16}/><input aria-label="Search activity" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clients, notes, outcomes…" style={{...field,border:0,background:'transparent',padding:5}}/></label><select aria-label="Filter interaction type" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} style={{...field,width:'auto',minWidth:150}}>{['All','Call','Meeting','Email','WhatsApp','Demo','Other'].map(x=><option key={x}>{x}</option>)}</select></div>
   {!visible.length?<div style={{...card,textAlign:'center',padding:28}}><History size={25} style={{margin:'0 auto 8px'}}/><h3 style={{margin:'0 0 6px'}}>No activity found</h3><p style={{...muted,margin:0}}>{items.length?'Try another search or filter.':'Log your first client interaction above to start building a history.'}</p></div>:visible.map(x=><article key={x.id} style={{...card,display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div><h3 style={{fontSize:17,margin:'0 0 4px'}}>{x.client}</h3><div style={muted}>{dateLabel(x.date)} · {x.type} · {x.outcome}</div></div><button type="button" onClick={()=>remove(x.id)} aria-label={'Delete activity for '+x.client} title="Delete interaction" style={{display:'inline-flex',alignItems:'center',gap:6,padding:8,borderRadius:8,border:'1px solid var(--viz-border, #333)',background:'transparent',color:'inherit',cursor:'pointer'}}><Trash2 size={15}/></button></div><p style={{margin:0,whiteSpace:'pre-wrap',lineHeight:1.6}}>{x.summary}</p>{x.nextAction&&<div style={{...muted,borderTop:'1px solid var(--viz-border, #333)',paddingTop:9}}><strong style={{color:'var(--viz-text, #f5f5f5)'}}>Next action:</strong> {x.nextAction}{x.nextDate?' · '+dateLabel(x.nextDate):''}</div>}</article>)}
  </section><p style={muted}>Privacy note: records stay in this browser's local storage and are not synced across devices. Avoid storing sensitive payment details or confidential personal information here.</p>
 </section>
}
