import { useEffect, useMemo, useState } from 'react';
import { CircleDollarSign, Copy, Download, Plus, ReceiptText, Trash2 } from 'lucide-react';
const PACKAGES_KEY='agencyos:sales-packages:v1';
const DEALS_KEY='agencyos:deal-tracker:v1';
const INVOICES_KEY='agencyos:invoice-tracker:v1';
const muted={color:'var(--viz-muted, #a1a1aa)',fontSize:13,lineHeight:1.55};
const field={width:'100%',boxSizing:'border-box',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'10px 11px',background:'var(--viz-card, #151515)',color:'var(--viz-text, #f5f5f5)',font:'inherit'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))??fallback}catch{return fallback}}
function amount(value){const n=Number(value);return Number.isFinite(n)&&n>0?n:0}
function money(value){return '₹'+Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
const blank={clientId:'',invoiceNo:'',amount:'',issueDate:today(),dueDate:'',status:'Draft',notes:''};
export default function InvoiceTracker(){
 const [packages,setPackages]=useState(()=>{const v=read(PACKAGES_KEY,[]);return Array.isArray(v)?v:[]});
 const [deals,setDeals]=useState(()=>{const v=read(DEALS_KEY,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}});
 const [invoices,setInvoices]=useState(()=>{const v=read(INVOICES_KEY,[]);return Array.isArray(v)?v:[]});
 const [form,setForm]=useState(blank);const [filter,setFilter]=useState('All');const [notice,setNotice]=useState('');
 const refresh=()=>{const p=read(PACKAGES_KEY,[]),d=read(DEALS_KEY,{});setPackages(Array.isArray(p)?p:[]);setDeals(d&&typeof d==='object'&&!Array.isArray(d)?d:{})};
 useEffect(()=>{const f=()=>refresh();window.addEventListener('focus',f);return()=>window.removeEventListener('focus',f)},[]);
 useEffect(()=>{try{localStorage.setItem(INVOICES_KEY,JSON.stringify(invoices))}catch{setNotice('Browser storage is full; invoice changes may not persist.')}},[invoices]);
 const clients=useMemo(()=>packages.filter(p=>(deals[p.id]||{}).stage==='Won'),[packages,deals]);
 const rows=invoices.filter(i=>filter==='All'||i.status===filter);
 const total=invoices.reduce((s,i)=>s+amount(i.amount),0);
 const paid=invoices.filter(i=>i.status==='Paid').reduce((s,i)=>s+amount(i.amount),0);
 const outstanding=invoices.filter(i=>['Sent','Overdue','Partially paid'].includes(i.status)).reduce((s,i)=>s+amount(i.amount),0);
 function create(e){e.preventDefault();if(!form.clientId||!form.invoiceNo.trim()||!amount(form.amount)){setNotice('Choose a won client and enter an invoice number and positive amount.');return}if(invoices.some(i=>i.invoiceNo.trim().toLowerCase()===form.invoiceNo.trim().toLowerCase())){setNotice('That invoice number already exists.');return}const client=clients.find(p=>p.id===form.clientId);setInvoices(prev=>[{...form,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),clientName:client?.businessName||'Client',service:client?.service||'Service',amount:String(amount(form.amount)),createdAt:new Date().toISOString()},...prev]);setForm({...blank,invoiceNo:'INV-'+new Date().getFullYear()+'-'+String(invoices.length+1).padStart(3,'0')});setNotice('Invoice record added. This does not issue or send a legal invoice.')}
 function update(id,patch){setInvoices(prev=>prev.map(i=>i.id===id?{...i,...patch}:i))}
 function remove(id){setInvoices(prev=>prev.filter(i=>i.id!==id));setNotice('Invoice record removed.')}
 async function copyReminder(inv){const due=inv.dueDate?' The due date was '+inv.dueDate+'.':'';const message='Hi '+(inv.clientName||'there')+', hope you are doing well. Just a friendly follow-up regarding invoice '+inv.invoiceNo+' for '+money(inv.amount)+'.'+due+' When convenient, could you please share an update on the payment? If you have already paid, please ignore this message. Thank you!';try{await navigator.clipboard.writeText(message);setNotice('Payment reminder copied. Review it before sending.')}catch{setNotice('Could not copy automatically. Check your browser clipboard permissions and try again.')}}
 function exportCsv(){const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[['Invoice','Client','Service','Amount INR','Issue date','Due date','Status','Notes'],...invoices.map(i=>[i.invoiceNo,i.clientName,i.service,i.amount,i.issueDate,i.dueDate,i.status,i.notes])].map(row=>row.map(esc).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='revoltz-invoice-tracker.csv';a.click();URL.revokeObjectURL(url)}
 return <div style={{display:'grid',gap:20,maxWidth:1100}}>
 <header style={{display:'flex',gap:13,alignItems:'flex-start'}}><div style={{border:'1px solid var(--viz-border, #333)',borderRadius:13,padding:12}}><ReceiptText size={23}/></div><div><div style={{...muted,letterSpacing:'.14em',fontWeight:700}}>REVOLTZ AI · BUSINESS ADMIN</div><h1 style={{fontSize:32,margin:'4px 0 7px'}}>Invoice & Payment Tracker</h1><p style={{...muted,margin:0}}>Track invoice records and payment status for confirmed clients. This is an internal tracker—not a tax invoice generator, payment gateway, or accounting system.</p></div></header>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}>{[['Invoice records',invoices.length],['Total recorded',money(total)],['Marked paid',money(paid)],['Outstanding',money(outstanding)]].map(([k,v])=><div key={k} style={{border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:14}}><div style={muted}>{k}</div><div style={{fontSize:23,fontWeight:750,marginTop:6}}>{v}</div></div>)}</div>
 {notice&&<div role="status" style={{...muted,border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:10}}>{notice}</div>}
 <form onSubmit={create} style={{border:'1px solid var(--viz-border, #333)',borderRadius:13,padding:16,display:'grid',gap:12}}><h2 style={{fontSize:19,margin:0}}>Add invoice record</h2>{!clients.length&&<p style={muted}>Mark a deal Won in Deal Pipeline before adding a client invoice record.</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,200px),1fr))',gap:10}}>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Confirmed client<select required style={field} value={form.clientId} onChange={e=>{const id=e.target.value;const suggested=deals[id]?.expectedValue||"";setForm(prev=>({...prev,clientId:id,amount:prev.amount||suggested}));}}><option value="">Choose a won client</option>{clients.map(p=><option key={p.id} value={p.id}>{p.businessName||'Business'} — {p.service||'Service'}</option>)}</select></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Invoice reference<input required maxLength={60} style={field} value={form.invoiceNo} onChange={e=>setForm({...form,invoiceNo:e.target.value})} placeholder="INV-2026-001"/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Amount (₹)<input required type="number" min="0.01" max="100000000" step="0.01" style={field} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Amount agreed with client"/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Issue date<input type="date" required style={field} value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Due date<input type="date" style={field} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Payment status<select style={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Draft','Sent','Partially paid','Paid','Overdue','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label>
 </div><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Notes<textarea rows={2} maxLength={2000} style={{...field,resize:'vertical'}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Payment reference or internal reminder"/></label><button type="submit" disabled={!clients.length} style={{justifySelf:'start',display:'inline-flex',gap:7,alignItems:'center',border:0,borderRadius:9,padding:'10px 13px',background:'var(--viz-accent, #3977dc)',color:'#fff',cursor:'pointer',opacity:clients.length?1:.5}}><Plus size={16}/> Add record</button></form>
 <section style={{display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><select aria-label="Filter invoice records" style={{...field,width:'auto',minWidth:180}} value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Draft','Sent','Partially paid','Paid','Overdue','Cancelled'].map(s=><option key={s}>{s}</option>)}</select><button type="button" disabled={!invoices.length} onClick={exportCsv} style={{display:'inline-flex',gap:7,alignItems:'center',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'9px 12px',background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer'}}><Download size={15}/> Export CSV</button></div>
 {!rows.length?<div style={{border:'1px dashed var(--viz-border, #444)',borderRadius:13,padding:24,textAlign:'center'}}><CircleDollarSign size={24}/><h2 style={{fontSize:19}}>No invoice records yet</h2><p style={{...muted,margin:0}}>Add an internal record above after confirming your agreement with the client.</p></div>:rows.map(inv=><article key={inv.id} style={{border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:14,display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{fontWeight:750,fontSize:17}}>{inv.invoiceNo} · {inv.clientName}</div><div style={muted}>{inv.service} · Issued {inv.issueDate||'not set'}{inv.dueDate?' · Due '+inv.dueDate:''}</div></div><div style={{fontWeight:750,fontSize:19}}>{money(inv.amount)}</div></div><div style={{display:'grid',gridTemplateColumns:'minmax(150px,220px) minmax(160px,1fr) auto auto',gap:9,alignItems:'center'}}><select aria-label={'Status for '+inv.invoiceNo} style={field} value={inv.status} onChange={e=>update(inv.id,{status:e.target.value})}>{['Draft','Sent','Partially paid','Paid','Overdue','Cancelled'].map(s=><option key={s}>{s}</option>)}</select><input aria-label={'Notes for '+inv.invoiceNo} style={field} value={inv.notes||''} maxLength={2000} onChange={e=>update(inv.id,{notes:e.target.value})} placeholder="Internal notes"/><button type="button" onClick={()=>copyReminder(inv)} disabled={!['Sent','Overdue','Partially paid'].includes(inv.status)} title="Copy payment reminder" aria-label={'Copy payment reminder for '+inv.invoiceNo} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6,border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:10,background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer',opacity:['Sent','Overdue','Partially paid'].includes(inv.status)?1:.45}}><Copy size={15}/></button><button type="button" aria-label={'Delete '+inv.invoiceNo} onClick={()=>remove(inv.id)} style={{border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:10,background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer'}}><Trash2 size={15}/></button></div></article>)}
 </section><p style={muted}>Stored only in this browser. Confirm applicable tax, invoicing and record-keeping requirements with a qualified professional. Do not enter sensitive payment credentials here.</p>
 </div>
}