import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Download, Plus, Trash2 } from 'lucide-react';
const KEY='agencyos:project-tracker:v1';
const PACKAGES_KEY='agencyos:sales-packages:v1';
const DEALS_KEY='agencyos:deal-tracker:v1';
const muted={color:'var(--viz-muted, #a1a1aa)',fontSize:13,lineHeight:1.55};
const field={width:'100%',boxSizing:'border-box',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'10px 11px',background:'var(--viz-card, #151515)',color:'var(--viz-text, #f5f5f5)',font:'inherit'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))??fallback}catch{return fallback}}
function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
const blank={clientId:'',title:'',status:'Not started',priority:'Normal',startDate:today(),dueDate:'',owner:'Me',notes:''};
const statuses=['Not started','In progress','Waiting on client','Review','Completed','On hold'];
export default function ProjectTracker(){
 const [packages,setPackages]=useState(()=>{const v=read(PACKAGES_KEY,[]);return Array.isArray(v)?v:[]});
 const [deals,setDeals]=useState(()=>{const v=read(DEALS_KEY,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}});
 const [projects,setProjects]=useState(()=>{const v=read(KEY,[]);return Array.isArray(v)?v:[]});
 const [form,setForm]=useState(blank);const [filter,setFilter]=useState('Active');const [notice,setNotice]=useState('');
 const refresh=()=>{const p=read(PACKAGES_KEY,[]),d=read(DEALS_KEY,{});setPackages(Array.isArray(p)?p:[]);setDeals(d&&typeof d==='object'&&!Array.isArray(d)?d:{})};
 useEffect(()=>{const f=()=>refresh();window.addEventListener('focus',f);return()=>window.removeEventListener('focus',f)},[]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(projects))}catch{setNotice('Browser storage is full; changes may not persist.')}},[projects]);
 const clients=useMemo(()=>packages.filter(p=>(deals[p.id]||{}).stage==='Won'),[packages,deals]);
 const shown=projects.filter(p=>filter==='All'||(filter==='Active'?!['Completed','On hold'].includes(p.status):p.status===filter));
 const stats=[['Projects',projects.length],['Active',projects.filter(p=>!['Completed','On hold'].includes(p.status)).length],['Overdue',projects.filter(p=>p.dueDate&&p.dueDate<today()&&p.status!=='Completed').length],['Completed',projects.filter(p=>p.status==='Completed').length]];
 function create(e){e.preventDefault();if(!form.title.trim()){setNotice('Enter a project or task title.');return}const client=clients.find(p=>p.id===form.clientId);setProjects(prev=>[{...form,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),clientName:client?.businessName||'Internal project',createdAt:new Date().toISOString()},...prev]);setForm({...blank,title:'',dueDate:''});setNotice('Project added.')}
 function update(id,patch){setProjects(prev=>prev.map(p=>p.id===id?{...p,...patch}:p))}
 function remove(id){setProjects(prev=>prev.filter(p=>p.id!==id));setNotice('Project removed.')}
 function exportCsv(){const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[['Project','Client','Status','Priority','Start date','Due date','Owner','Notes'],...projects.map(p=>[p.title,p.clientName,p.status,p.priority,p.startDate,p.dueDate,p.owner,p.notes])].map(row=>row.map(esc).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='revoltz-projects.csv';a.click();URL.revokeObjectURL(url)}
 return <div style={{display:'grid',gap:20,maxWidth:1100}}>
 <header style={{display:'flex',gap:13,alignItems:'flex-start'}}><div style={{border:'1px solid var(--viz-border, #333)',borderRadius:13,padding:12}}><CalendarDays size={23}/></div><div><div style={{...muted,letterSpacing:'.14em',fontWeight:700}}>REVOLTZ AI · DELIVERY OPERATIONS</div><h1 style={{fontSize:32,margin:'4px 0 7px'}}>Project Tracker</h1><p style={{...muted,margin:0}}>Organise client work, deadlines, priorities and internal tasks after a deal is confirmed.</p></div></header>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10}}>{stats.map(([k,v])=><div key={k} style={{border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:14}}><div style={muted}>{k}</div><div style={{fontSize:26,fontWeight:750,marginTop:6}}>{v}</div></div>)}</div>
 {notice&&<div role="status" style={{...muted,border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:10}}>{notice}</div>}
 <form onSubmit={create} style={{border:'1px solid var(--viz-border, #333)',borderRadius:13,padding:16,display:'grid',gap:12}}><h2 style={{fontSize:19,margin:0}}>Add project or task</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,190px),1fr))',gap:10}}>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Project / task title<input required maxLength={160} style={field} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Build client landing page"/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Client (optional)<select style={field} value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Internal project</option>{clients.map(p=><option key={p.id} value={p.id}>{p.businessName||'Business'}</option>)}</select></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Priority<select style={field} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['Low','Normal','High','Urgent'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Status<select style={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(v=><option key={v}>{v}</option>)}</select></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Start date<input type="date" style={field} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Due date<input type="date" style={field} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label>
 <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Owner<input maxLength={100} style={field} value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label>
 </div><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Notes<textarea rows={2} maxLength={3000} style={{...field,resize:'vertical'}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Next step, blockers, or deliverables"/></label><button type="submit" style={{justifySelf:'start',display:'inline-flex',gap:7,alignItems:'center',border:0,borderRadius:9,padding:'10px 13px',background:'var(--viz-accent, #3977dc)',color:'#fff',cursor:'pointer'}}><Plus size={16}/> Add project</button></form>
 <section style={{display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><select aria-label="Filter projects" style={{...field,width:'auto',minWidth:180}} value={filter} onChange={e=>setFilter(e.target.value)}>{['Active','All',...statuses].map(v=><option key={v}>{v}</option>)}</select><button type="button" disabled={!projects.length} onClick={exportCsv} style={{display:'inline-flex',gap:7,alignItems:'center',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'9px 12px',background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer'}}><Download size={15}/> Export CSV</button></div>
 {!shown.length?<div style={{border:'1px dashed var(--viz-border, #444)',borderRadius:13,padding:24,textAlign:'center'}}><h2 style={{fontSize:19}}>No projects in this view</h2><p style={{...muted,margin:0}}>Add a project or task above to start tracking delivery.</p></div>:shown.map(p=><article key={p.id} style={{border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:14,display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{fontWeight:750,fontSize:17}}>{p.title}</div><div style={muted}>{p.clientName} · Owner: {p.owner||'Unassigned'} · Priority: {p.priority}</div><div style={{...muted,marginTop:4}}>{p.dueDate?'Due '+p.dueDate+(p.dueDate<today()&&p.status!=='Completed'?' · OVERDUE':''):'No due date'}</div></div><button type="button" aria-label={'Delete '+p.title} onClick={()=>remove(p.id)} style={{border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:9,height:38,background:'transparent',color:'var(--viz-text, #fff)',cursor:'pointer'}}><Trash2 size={15}/></button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:9}}><label style={{display:'grid',gap:5,fontSize:12,fontWeight:650}}>Status<select style={field} value={p.status} onChange={e=>update(p.id,{status:e.target.value})}>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label style={{display:'grid',gap:5,fontSize:12,fontWeight:650}}>Due date<input type="date" style={field} value={p.dueDate||''} onChange={e=>update(p.id,{dueDate:e.target.value})}/></label><label style={{display:'grid',gap:5,fontSize:12,fontWeight:650}}>Notes<input style={field} maxLength={3000} value={p.notes||''} onChange={e=>update(p.id,{notes:e.target.value})}/></label></div></article>)}
 </section><p style={muted}>Projects are stored in this browser only. Export CSV for a backup; records are not shared across devices or team members.</p>
 </div>
}