import { useEffect, useState } from 'react';
import { FileSignature, Copy, Download, Trash2, Eye, Sparkles } from 'lucide-react';

const KEY='agencyos:proposal-builder:v1';
const field={width:'100%',boxSizing:'border-box',border:'1px solid var(--viz-border, #333)',borderRadius:9,padding:'10px 11px',background:'var(--viz-card, #151515)',color:'var(--viz-text, #f5f5f5)',font:'inherit'};
const card={border:'1px solid var(--viz-border, #333)',borderRadius:12,padding:16,background:'var(--viz-card, #151515)'};
const muted={color:'var(--viz-muted, #a1a1aa)',fontSize:13,lineHeight:1.6};
const initial=()=>({client:'',business:'',service:'Website design and development',price:'',currency:'INR',startDate:'',deliveryDays:'14',revisions:'2',paymentTerms:'50% upfront, 50% before handover',scope:'Responsive website\nContact form\nBasic on-page SEO',exclusions:'Paid hosting, domain, premium plugins, and ongoing maintenance unless agreed separately',milestones:'Discovery and content collection\nDesign approval\nDevelopment and review\nFinal testing and handover',notes:'',validDays:'14',brandColor:'#7c3aed',packageTier:'Custom',includeAnalytics:true,includeTraining:true,includeHostingSetup:false,includeMaintenance:false,brandTagline:'A clear plan. A confident launch.'});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...initial(),...(x&&typeof x==='object'?x:{})}}catch{return initial()}}
export default function ProposalBuilder(){
 const [form,setForm]=useState(load);const [notice,setNotice]=useState('');const [previewMode,setPreviewMode]=useState('document');
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(form))}catch{setNotice('Browser storage is full; changes may not save.')}},[form]);
 const set=(k,v)=>setForm(old=>({...old,[k]:v}));
 const money=form.price?new Intl.NumberFormat('en-IN',{style:'currency',currency:form.currency,maximumFractionDigits:0}).format(Number(form.price)||0):'To be agreed';
 const lines=(value)=>String(value||'').split('\n').map(x=>x.trim()).filter(Boolean);
 const extras=[form.includeAnalytics?'Analytics and basic performance tracking setup':null,form.includeTraining?'Handover walkthrough and basic training':null,form.includeHostingSetup?'Hosting/domain setup assistance (third-party fees excluded)':null,form.includeMaintenance?'Post-launch maintenance (details to be agreed)':null].filter(Boolean);
 const allScope=[...lines(form.scope),...extras];
 const proposal=`PROJECT PROPOSAL & SCOPE OF WORK\n\nPrepared for: ${form.client||'[Client name]'}\nBusiness: ${form.business||'[Business name]'}\nService: ${form.service}\nDate: ${new Date().toLocaleDateString('en-IN')}\nValidity: ${form.validDays||14} days\n\n1. PROJECT OVERVIEW\nThis proposal outlines the intended deliverables, timeline, and commercial terms. Final scope begins only after both parties approve the terms in writing.\n\n2. SCOPE & DELIVERABLES\n${lines(form.scope).map(x=>'• '+x).join('\n')||'To be confirmed'}\n\n3. MILESTONES\n${lines(form.milestones).map((x,i)=>(i+1)+'. '+x).join('\n')||'To be confirmed'}\n\n4. TIMELINE\nEstimated delivery: ${form.deliveryDays||'To be agreed'} calendar days after required content, access, and initial payment are received. Delays in feedback or materials may affect delivery.\n\n5. FEES & PAYMENT\nProject fee: ${money}\nPayment terms: ${form.paymentTerms||'To be agreed in writing'}\nWork may pause if agreed payments are overdue. Any taxes, third-party fees, or additional work should be confirmed separately.\n\n6. REVISIONS\nIncluded revision rounds: ${form.revisions||'To be agreed'}. A revision round means a consolidated set of changes within the agreed scope. New features or scope changes may require a separate quote.\n\n7. EXCLUSIONS & CLIENT RESPONSIBILITIES\n${form.exclusions||'Items outside the agreed scope will be quoted separately.'}\nThe client is responsible for timely content, approvals, and access to required accounts.\n\n8. ADDITIONAL NOTES\n${form.notes||'None'}\n\n9. ACCEPTANCE\nClient name: ____________________   Date: __________\nAgency representative: __________   Date: __________\n\nThis is a working proposal template, not legal or tax advice. Review and adapt it to the project and applicable law before signing.`;
 async function copy(){try{await navigator.clipboard.writeText(proposal);setNotice('Proposal copied. Review and customize before sharing.')}catch{setNotice('Clipboard access was blocked. Use Export TXT instead.')}}
 function exportTxt(){const url=URL.createObjectURL(new Blob([proposal],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='revoltz-project-proposal.txt';a.click();URL.revokeObjectURL(url);setNotice('Proposal exported as TXT.')}
 const input=(label,key,placeholder='',type='text')=><label style={{display:'grid',gap:6}}>{label}<input style={field} type={type} value={form[key]} onChange={e=>set(key,e.target.value)} placeholder={placeholder} /></label>;
 const area=(label,key,help)=><label style={{display:'grid',gap:6}}>{label}<textarea style={{...field,minHeight:100,resize:'vertical'}} value={form[key]} onChange={e=>set(key,e.target.value)} />{help&&<span style={muted}>{help}</span>}</label>;
 return <section style={{display:'grid',gap:16,color:'var(--viz-text, #f5f5f5)'}}>
  <div><div style={{display:'flex',alignItems:'center',gap:8,color:'#a78bfa',fontSize:12,fontWeight:800,letterSpacing:1.5,marginBottom:8}}><Sparkles size={15}/> REVOLTZ STUDIO</div><h2 style={{margin:'0 0 6px',display:'flex',alignItems:'center',gap:9}}><FileSignature size={22}/> Proposal Studio</h2><p style={{...muted,margin:0}}>Draft a clear project proposal with deliverables, milestones, fees and boundaries. Nothing is sent automatically.</p></div>
  <div style={{...card,display:'grid',gap:14}}>
   <h3 style={{margin:0}}>Client & project</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{input('Client contact','client','Client name')}{input('Client business','business','Business name')}<label style={{display:'grid',gap:6}}>Service<input style={field} value={form.service} onChange={e=>set('service',e.target.value)} placeholder="Website, SEO, automation..." /></label>{input('Project fee','price','e.g. 15000','number')}<label style={{display:'grid',gap:6}}>Currency<select style={field} value={form.currency} onChange={e=>set('currency',e.target.value)}><option value="INR">INR ₹</option><option value="USD">USD $</option><option value="GBP">GBP £</option><option value="EUR">EUR €</option></select></label>{input('Estimated delivery (days)','deliveryDays','14','number')}{input('Revision rounds','revisions','2','number')}{input('Proposal validity (days)','validDays','14','number')}</div>
   {area('Deliverables (one per line)','scope')}{area('Milestones (one per line)','milestones')}{input('Payment terms','paymentTerms','50% upfront, 50% before handover')}{area('Exclusions & client responsibilities','exclusions')}{area('Additional notes','notes')}
   <div style={{display:'flex',flexWrap:'wrap',gap:8}}><button type="button" className="button button-primary" onClick={copy}><Copy size={15}/> Copy proposal</button><button type="button" className="button button-secondary" onClick={exportTxt}><Download size={15}/> Export TXT</button><button type="button" className="button button-secondary" onClick={()=>{setForm(initial());setNotice('Form reset.');}}><Trash2 size={15}/> Reset form</button></div>{notice&&<p role="status" style={{...muted,margin:0}}>{notice}</p>}
  </div>
  <div style={card}><h3 style={{margin:'0 0 8px'}}>Proposal preview</h3><p style={muted}>Estimated fee: <strong style={{color:'var(--viz-text, #f5f5f5)'}}>{money}</strong> · {form.deliveryDays||'—'} days · {form.revisions||'—'} revision rounds</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',font:'inherit',fontSize:13,lineHeight:1.65,maxHeight:460,overflow:'auto',margin:0}}>{proposal}</pre></div>
 </section>;
}
