import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Download, ExternalLink, Plus, Trash2, Globe2, RotateCcw } from 'lucide-react';

const KEY = 'agencyos:website-delivery:v1';
const muted = { color: 'var(--viz-muted, #a1a1aa)', fontSize: 13, lineHeight: 1.55 };
const field = { width: '100%', boxSizing: 'border-box', border: '1px solid var(--viz-border, #333)', borderRadius: 9, padding: '10px 11px', background: 'var(--viz-card, #151515)', color: 'var(--viz-text, #f5f5f5)', font: 'inherit' };
const card = { border: '1px solid var(--viz-border, #333)', borderRadius: 12, padding: 14 };
const phases = ['Not started', 'In progress', 'Waiting for client', 'Ready to launch', 'Launched'];
const defaultTasks = ['Confirm scope and price', 'Collect logo, photos and brand details', 'Confirm page copy and contact details', 'Check mobile layout', 'Test navigation and buttons', 'Test contact form or contact links', 'Check page title and description', 'Confirm client approval', 'Connect domain and hosting', 'Send handover instructions'];
const blank = { client: '', project: 'Business website', demoUrl: '', liveUrl: '', deadline: '', phase: 'Not started', approval: 'Not requested', revisionLimit: '2', revisionsUsed: '0', nextAction: '', handover: '', tasks: defaultTasks.map((title, i) => ({ id: String(i + 1), title, done: false })) };
const read = () => { try { const v = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(v) ? v.filter(x => x && typeof x.id === 'string') : []; } catch { return []; } };
const safeUrl = value => { try { const u = new URL(value); return ['http:', 'https:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } };
function exportCsv(items) { const esc = v => '"' + String(v ?? '').replace(/"/g, '""') + '"'; const rows = [['Client','Project','Phase','Approval','Deadline','Demo URL','Live URL','Revisions used','Revision limit','Next action','Handover notes','Checklist done','Checklist total'], ...items.map(x => [x.client,x.project,x.phase,x.approval,x.deadline,x.demoUrl,x.liveUrl,x.revisionsUsed,x.revisionLimit,x.nextAction,x.handover,(x.tasks||[]).filter(t=>t.done).length,(x.tasks||[]).length])]; const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})); const a=document.createElement('a'); a.href=url; a.download='agencyos-website-delivery.csv'; a.click(); URL.revokeObjectURL(url); }
export default function WebsiteDelivery() {
 const [items,setItems]=useState(read);
 const [form,setForm]=useState({...blank,tasks:defaultTasks.map((title,i)=>({id:String(i+1),title,done:false}))});
 const [notice,setNotice]=useState('');
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(items));}catch{setNotice('Browser storage is full; changes may not persist.')}},[items]);
 const stats=useMemo(()=>({total:items.length,launch:items.filter(x=>x.phase==='Ready to launch').length,live:items.filter(x=>x.phase==='Launched').length,waiting:items.filter(x=>x.phase==='Waiting for client').length}),[items]);
 function add(e){e.preventDefault();if(!form.client.trim()){setNotice('Enter a client or business name first.');return;}const entry={...form,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),client:form.client.trim(),createdAt:new Date().toISOString()};setItems(p=>[entry,...p]);setForm({...blank,tasks:defaultTasks.map((title,i)=>({id:String(i+1),title,done:false}))});setNotice('Delivery project created and saved in this browser.');}
 function update(id,patch){setItems(p=>p.map(x=>x.id===id?{...x,...patch}:x));}
 function toggleTask(projectId,taskId){setItems(p=>p.map(x=>x.id!==projectId?x:{...x,tasks:(x.tasks||[]).map(t=>t.id===taskId?{...t,done:!t.done}:t)}));}
 return <section style={{display:'grid',gap:16,maxWidth:1100,color:'var(--viz-text, #f5f5f5)'}}>
  <header style={{display:'flex',gap:12,alignItems:'flex-start'}}><div style={{...card,padding:12}}><ClipboardCheck size={23}/></div><div><div style={{...muted,letterSpacing:'.13em',fontWeight:700}}>REVOLTZ AI · CLIENT DELIVERY</div><h1 style={{fontSize:30,margin:'4px 0 6px'}}>Website Delivery Hub</h1><p style={{...muted,margin:0}}>Manage each website from client approval through launch and handover—with a practical checklist and revision tracking.</p></div></header>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{[['Projects',stats.total],['Ready to launch',stats.launch],['Launched',stats.live],['Waiting on client',stats.waiting]].map(([label,value])=><div key={label} style={card}><div style={muted}>{label}</div><div style={{fontSize:23,fontWeight:750,marginTop:6}}>{value}</div></div>)}</div>
  {notice&&<div role="status" style={{...card,...muted}}>{notice}</div>}
  <form onSubmit={add} style={{...card,display:'grid',gap:12}}><h2 style={{fontSize:19,margin:0}}>Create delivery project</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,190px),1fr))',gap:10}}>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Client / business<input required maxLength={140} style={field} value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Client name"/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Project type<input maxLength={120} style={field} value={form.project} onChange={e=>setForm({...form,project:e.target.value})}/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Demo / preview URL<input maxLength={1000} type="url" style={field} value={form.demoUrl} onChange={e=>setForm({...form,demoUrl:e.target.value})} placeholder="https://..."/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Live website URL<input maxLength={1000} type="url" style={field} value={form.liveUrl} onChange={e=>setForm({...form,liveUrl:e.target.value})} placeholder="https://..."/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Target launch date<input type="date" style={field} value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Delivery phase<select style={field} value={form.phase} onChange={e=>setForm({...form,phase:e.target.value})}>{phases.map(x=><option key={x}>{x}</option>)}</select></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Client approval<select style={field} value={form.approval} onChange={e=>setForm({...form,approval:e.target.value})}>{['Not requested','Awaiting feedback','Changes requested','Approved'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Revision allowance<input type="number" min="0" max="100" style={field} value={form.revisionLimit} onChange={e=>setForm({...form,revisionLimit:e.target.value})}/></label>
  </div><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Next action<input maxLength={300} style={field} value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})} placeholder="e.g. Ask client to approve homepage"/></label><label style={{display:'grid',gap:6,fontSize:13,fontWeight:650}}>Handover notes<textarea rows={2} maxLength={2000} style={{...field,resize:'vertical'}} value={form.handover} onChange={e=>setForm({...form,handover:e.target.value})} placeholder="Hosting, domain, access and maintenance notes (do not store passwords)"/></label><button type="submit" style={{justifySelf:'start',display:'inline-flex',gap:7,alignItems:'center',border:0,borderRadius:9,padding:'10px 13px',background:'var(--viz-accent, #3977dc)',color:'#fff',cursor:'pointer'}}><Plus size={16}/> Create project</button></form>
  <div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><strong style={{fontSize:18}}>Delivery projects</strong><button type="button" onClick={()=>exportCsv(items)} disabled={!items.length} style={{...field,width:'auto',display:'inline-flex',gap:7,alignItems:'center',marginLeft:'auto',cursor:'pointer'}}><Download size={15}/> Export CSV</button></div>
  {!items.length?<div style={{...card,textAlign:'center',padding:25}}><Globe2 size={26}/><h2 style={{fontSize:19}}>No delivery projects yet</h2><p style={{...muted,margin:0}}>Create one above to track client feedback, revisions and launch readiness.</p></div>:items.map(x=>{const tasks=x.tasks||[];const done=tasks.filter(t=>t.done).length;const used=Number(x.revisionsUsed||0);const limit=Number(x.revisionLimit||0);return <article key={x.id} style={{...card,display:'grid',gap:13}}><div style={{display:'flex',gap:12,justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap'}}><div style={{minWidth:220,flex:1}}><strong style={{fontSize:19}}>{x.client}</strong><div style={muted}>{x.project}{x.deadline?' · Target '+x.deadline:''}</div><div style={{...muted,marginTop:5}}>{done}/{tasks.length} launch checks complete</div><div style={{height:5,background:'var(--viz-border, #333)',borderRadius:9,overflow:'hidden',marginTop:7,maxWidth:400}}><div style={{height:'100%',width:(tasks.length?done/tasks.length*100:0)+'%',background:'var(--viz-accent, #3977dc)'}}/></div></div><div style={{display:'grid',gap:8,minWidth:190}}><label style={{display:'grid',gap:4,fontSize:12}}>Phase<select style={field} value={x.phase} onChange={e=>update(x.id,{phase:e.target.value})}>{phases.map(s=><option key={s}>{s}</option>)}</select></label><label style={{display:'grid',gap:4,fontSize:12}}>Client approval<select style={field} value={x.approval} onChange={e=>update(x.id,{approval:e.target.value})}>{['Not requested','Awaiting feedback','Changes requested','Approved'].map(s=><option key={s}>{s}</option>)}</select></label></div></div>
   <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{safeUrl(x.demoUrl)&&<a href={safeUrl(x.demoUrl)} target="_blank" rel="noreferrer" style={{...field,width:'auto',display:'inline-flex',alignItems:'center',gap:6,textDecoration:'none'}}><ExternalLink size={14}/> Open demo</a>}{safeUrl(x.liveUrl)&&<a href={safeUrl(x.liveUrl)} target="_blank" rel="noreferrer" style={{...field,width:'auto',display:'inline-flex',alignItems:'center',gap:6,textDecoration:'none'}}><Globe2 size={14}/> Open live site</a>}<span style={{...muted,alignSelf:'center'}}>Revisions: {used} used / {limit} allowed</span><button type="button" onClick={()=>update(x.id,{revisionsUsed:String(Math.min(1000,used+1))})} style={{...field,width:'auto',display:'inline-flex',gap:6,alignItems:'center',cursor:'pointer'}}><RotateCcw size={14}/> Log revision</button><button type="button" onClick={()=>update(x.id,{revisionsUsed:String(Math.max(0,used-1))})} disabled={used===0} style={{...field,width:'auto',cursor:'pointer'}}>Undo</button><button type="button" onClick={()=>{if(confirm('Delete this delivery project?'))setItems(p=>p.filter(y=>y.id!==x.id))}} style={{...field,width:'auto',display:'inline-flex',gap:6,alignItems:'center',marginLeft:'auto',cursor:'pointer'}}><Trash2 size={14}/> Delete</button></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,250px),1fr))',gap:12}}><div style={{...card,display:'grid',gap:8}}><strong>Launch checklist</strong>{tasks.map(t=><label key={t.id} style={{display:'flex',gap:8,alignItems:'flex-start',fontSize:13,cursor:'pointer'}}><input type="checkbox" checked={Boolean(t.done)} onChange={()=>toggleTask(x.id,t.id)} style={{marginTop:3}}/><span style={{textDecoration:t.done?'line-through':'none',opacity:t.done?.65:1}}>{t.title}</span></label>)}</div><div style={{...card,display:'grid',gap:9,alignContent:'start'}}><strong>Client handover & next step</strong><label style={{display:'grid',gap:5,fontSize:12}}>Next action<input maxLength={300} style={field} value={x.nextAction||''} onChange={e=>update(x.id,{nextAction:e.target.value})} placeholder="What happens next?"/></label><label style={{display:'grid',gap:5,fontSize:12}}>Handover notes<textarea rows={4} maxLength={2000} style={{...field,resize:'vertical'}} value={x.handover||''} onChange={e=>update(x.id,{handover:e.target.value})} placeholder="Record domain, hosting, maintenance and training details. Never store passwords."/></label>{x.phase==='Launched'&&x.approval!=='Approved'&&<div style={{...muted,display:'flex',gap:6}}><CheckCircle2 size={15}/> Mark client approval once confirmed; keep a record of any outstanding items.</div>}</div></div>
  </article>})}
  <p style={muted}>Data saves in this browser only and does not publish, host or modify a website. Share demo/live links with clients separately. Do not store passwords, API keys or private access credentials here.</p>
 </section>;
}
